version: '3'
services:
  dse1:
    image: datastax/dse-server:6.7.7
    command: []
    environment:
      DS_LICENSE: accept
    ports:
      - 7076:7077
      - 9042:9042
      - 4040:4040
      - 8082:8080
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  dse2:
    image: datastax/dse-server:6.7.7
    depends_on:
      - dse1
    command: []
    environment:
      DS_LICENSE: accept
      SEEDS: dse1
    links:
      - dse1
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
